# Generated by Django 5.2.7 on 2025-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=255)),
                ('original_url', models.URLField()),
                ('short_string', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
